---
title: "Load data from web and unzip it"
output:
  html_notebook: default
  html_document: default
---

# Load packages

```{r echo=TRUE}
library(downloader)
library(knitr)
```
$~$
$~$

# R setup
Change working directory to my target directory.
Hint: [Github does not allow to upload files larger than 100 MB](https://help.github.com/articles/working-with-large-files/). Therefore our target directory needs to be local or in a suitable online data system.
```{r "setup", echo=TRUE}
require("knitr")
opts_knit$set(root.dir = "/Users/Ramon/Documents/R/DS Capstone Project/")
```
$~$
$~$

# Load data

We need to load the data from [this URL](https://d396qusza40orc.cloudfront.net/dsscapstone/dataset/Coursera-SwiftKey.zip). Afterwards we unzip it so we can better accesss it.
```{r}
url <- "https://d396qusza40orc.cloudfront.net/dsscapstone/dataset/Coursera-SwiftKey.zip"
download(url, dest="dataset.zip", mode="wb") 
unzip ("dataset.zip")
#get target folder name containing all important files
list.files()[grep(pattern = "final", x = list.files())]
```

The folder name containing all files is "final".